apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: full-stack-app
  labels:
    app: backend
    component: api
    tier: backend
spec:
  replicas: {{ .Values.replicas.backend }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        component: api
        tier: backend
    spec:
      containers:
      - name: backend
        image: {{ .Values.images.backend.repository }}:{{ .Values.images.backend.tag }}
        ports:
        - containerPort: 5001
        
        resources:
          {{- toYaml .Values.resources.backend | nindent 10 }}

        # Kubernetes Health Checks
        livenessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3

        env:
        - name: NODE_ENV
          value: {{ .Values.env.nodeEnv }}
        - name: MONGODB_URI
          value: "mongodb://{{ .Values.mongodb.auth.username }}:{{ .Values.mongodb.auth.password }}@mongodb-service:27017/{{ .Values.mongodb.auth.database }}?authSource=admin"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef: 
              name: secrets
              key: jwt 
        - name: PORT
          value: "5001"
