apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: full-stack-app
  labels:
    app: mongodb
    component: database
    tier: data
spec:
  replicas: {{ .Values.replicas.mongodb }}
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
        component: database
        tier: data
    spec:
      containers:
      - name: mongodb
        image: {{ .Values.images.mongodb.repository }}:{{ .Values.images.mongodb.tag }}
        ports:
        - containerPort: 27017
        
        resources:
          {{- toYaml .Values.resources.mongodb | nindent 10 }}
        
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db

        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: {{ .Values.mongodb.auth.username }}
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: {{ .Values.mongodb.auth.password }}

      volumes: 
      - name: mongo-data
        persistentVolumeClaim:
          claimName: mongodb-pvc
