apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  namespace: full-stack-app
spec:
  capacity:
    storage: {{ .Values.mongodb.storage.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.mongodb.storage.path }}
