apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: full-stack-app
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: full-stack-frontend
        image: mayurj023/full-stack_frontend:latest
        ports:
        - containerPort: 80
        
        # Resource limits for frontend
        resources:
          requests:
            memory: "32Mi"    
            cpu: "25m"        
          limits:
            memory: "64Mi"    
            cpu: "100m"       

        env:
        - name: NODE_ENV
          value: production 
