apiVersion: v1
kind: Service
metadata:
  name: backend  # Changed from backend-service to backend
  namespace: full-stack-app
  labels:
    app: backend
    component: api
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
  - name: http
    port: 5001
    targetPort: 5001
    protocol: TCP
