apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: full-stack-app
  labels:
    app: frontend
    component: web
    tier: frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP
