apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: full-stack-app
  labels:
    app: mongodb
    component: database
    tier: data
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
  - name: mongodb
    port: 27017
    targetPort: 27017
    protocol: TCP
