# =============================================================================
# Full Stack Application - Helm Chart Configuration
# =============================================================================
# This file contains the default configuration values for the full-stack app
# Override these values using -f values-dev.yaml or --set key=value

# =============================================================================
# CONTAINER IMAGES
# =============================================================================
# Configure Docker images for each component
images:
  backend:
    repository: mayurj023/full-stack_backend
    tag: latest
    pullPolicy: IfNotPresent
  
  frontend:
    repository: mayurj023/full-stack_frontend
    tag: latest
    pullPolicy: IfNotPresent
  
  mongodb:
    repository: mongo
    tag: latest
    pullPolicy: IfNotPresent

# =============================================================================
# REPLICA COUNTS
# =============================================================================
# Number of pod replicas for each component
replicas:
  backend: 1    # API server instances
  frontend: 1   # Web server instances  
  mongodb: 1    # Database instances (keep at 1 unless clustering)

# =============================================================================
# RESOURCE LIMITS
# =============================================================================
# CPU and memory limits for each component
resources:
  backend:
    requests:
      memory: "128Mi"  # Guaranteed memory
      cpu: "100m"      # Guaranteed CPU (0.1 core)
    limits:
      memory: "512Mi"  # Maximum memory
      cpu: "500m"      # Maximum CPU (0.5 core)
  
  frontend:
    requests:
      memory: "32Mi"   # Lightweight static server
      cpu: "25m"       # Minimal CPU needs
    limits:
      memory: "64Mi"   # Small memory footprint
      cpu: "100m"      # Sufficient for nginx
  
  mongodb:
    requests:
      memory: "256Mi"  # Database operations
      cpu: "200m"      # Query processing
    limits:
      memory: "1Gi"    # Caching and working memory
      cpu: "1000m"     # Full core for complex queries

# =============================================================================
# ENVIRONMENT VARIABLES
# =============================================================================
# Application environment configuration
env:
  nodeEnv: production  # NODE_ENV value for all containers

# =============================================================================
# DATABASE CONFIGURATION
# =============================================================================
# MongoDB settings and storage
mongodb:
  # Authentication
  auth:
    username: mongodbadmin
    password: secret
    database: dbname
  
  # Persistent storage
  storage:
    size: 5Gi        # Storage size for database
    path: /datal     # Host path (Minikube specific)

# =============================================================================
# SECRETS
# =============================================================================
# Application secrets (base64 encode these in production)
secrets:
  jwt: Ouz5qSV4YoSdLC+8aaNeTNUWyIiKWWM01mQq8oFHutY=
